# This code is generated by chatGPT to check if your GPU and Python environment supports Automatic Mixed Precision (AMP) in PyTorch.
import torch

print("PyTorch version:", torch.__version__)

# Check if CUDA is available
if not torch.cuda.is_available():
    print("❌ CUDA is not available. Mixed precision requires a CUDA-capable GPU.")
else:
    print("✅ CUDA is available.")

    # Get device name
    device_name = torch.cuda.get_device_name(0)
    print("GPU:", device_name)

    # Check Compute Capability
    capability = torch.cuda.get_device_capability(0)
    print("Compute Capability:", capability)

    # Check AMP (automatic mixed precision) support
    if capability >= (7, 0):
        print("✅ Your GPU supports mixed precision (Tensor Cores available).")
    else:
        print("⚠️ Your GPU may not support mixed precision efficiently (Tensor Cores not available).")

    # Try using AMP
    try:
        with torch.cuda.amp.autocast():
            x = torch.rand((2, 2), device='cuda')
            y = x @ x
            print("✅ AMP test succeeded. Mixed precision is usable.")
    except Exception as e:
        print("❌ AMP test failed:", e)
