#!/bin/bash
#SBATCH --job-name=ti
#SBATCH --output=slurm_logs_tinyimagenet/job_%A_%a.out
#SBATCH --array=0-7
#SBATCH --partition=gpu
#SBATCH --nodes 1
#SBATCH --gres=gpu:1
#SBATCH --time=13:00:00
#SBATCH --mem=20G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6

conda init
conda activate focal_scaling

SAVE_PATH="../MODEL_DIRECTORY/TINYIMAGENET/"
SMOKE_ARG="--smoke-test" # to test that everything is running correctly. otherwise set it to empty string ""
AMP_ARG="--amp" # run with automatic mixed precision enabled or not. If not set it to empty string ""

case $SLURM_ARRAY_TASK_ID in
  0)
    ARGS="--loss cross_entropy"
    ;;
  1)
    ARGS="--loss focal_loss --gamma 1.0"
    ;;
  2)
    ARGS="--loss focal_loss --gamma 2.0"
    ;;
  3)
    ARGS="--loss focal_loss --gamma 3.0"
    ;;
  4)
    ARGS="--loss focal_loss --gamma 5.0"
    ;;
  5)
    ARGS="--loss focal_loss --gamma 7.0"
    ;;
  6)
    ARGS="--loss focal_loss_adaptive --gamma 3.0"
    ;;
  7)
    ARGS="--loss adafocal"
    ;;
  *)
    echo "Invalid array index $SLURM_ARRAY_TASK_ID"
    exit 1
    ;;
esac

python ../train.py --dataset tiny_imagenet --model resnet50_ti --dataset-root ../TINY_IMAGENET_DIRECTORY --first-milestone 40 --second-milestone 60 -e 100 -b 64 -tb 64 $ARGS --decay 0.0005 -g $AMP --save-path $SAVE_PATH $SMOKE_ARG
